AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template launches an EC-2 instance with a security group that enables ssh connection.
Resources:
  Webserver:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b5eea76982371e91
      InstanceType: t2.micro
      KeyName: sample-key
      SecurityGroups:
        - !Ref WebserverSecGrp
      Tags:
        - Key: Name
          Value: CFN-Instance
        - Key: Environment
          Value: Dev
  
  WebserverSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: enables ssh connection
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0